version: 2

sphinx:
  configuration: conf.py

formats: []

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
    - requirements: requirements.txt
